version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running security checks..."
      - npx eslint . --ext .js,.jsx
      - npx snyk test
      - echo "Security checks complete."
  build:
    commands:
      - echo "Building frontend..."
      - npm run build
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - '**/*'
  base-directory: 'build'

