version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running security scans..."
      - npx eslint . --ext .js
      - npx snyk test
      - npx cycode scan --exit-code 1
      - echo "Checking for exposed API endpoints..."
      - if grep -q "EXPOSED_API_ENDPOINT_PATTERN" src/app.js; then echo "API Exposure Detected! Failing build."; exit 1; fi
  build:
    commands:
      - echo "Building backend..."
      - npm run build
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
